# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Revista Agreste
email: revistaagreste@gmail.com
description: __AGRESTE - Agrupamento de Estudos Excêntricxs__ está sendo construída por realizadorxs que problematizam e buscam redefinir sua condição marginal de produtores simbólicos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "agre.st" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Collections
collections:
  ed1:
    output: true
    permalink: /1/:title
  ed1_especiais:
    output: true
    permalink: /1/:title
  ed2:
    output: true
    permalink: /2/:title
  ed2_especiais:
    output: true
    permalink: /2/:title
  globals:
    output: true
    permalink: /:title

# Build settings
markdown: kramdown
permalink: /:title
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
